name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node env
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build Project
        run: yarn && yarn build

      - name: Setup OSS
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Deploy to OSS
        run: |
          ossutil rm -rf oss://${{ secrets.OSS_TARGET_BUCKET }}/
          ossutil cp -rf public/  oss://${{ secrets.OSS_TARGET_BUCKET }}/
